spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/denguetrace_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=${SHOW_SQL:false}

jwt.secret=${JWT_SECRET}
jwt.access-expiration-ms=900000
jwt.refresh-expiration-ms=604800000
dni.hash.secret=${DNI_HASH_SECRET}